=== api-evangelist/google-cloud-healthcare/json-schema/Hl7V2Store.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Hl7V2Store",
  "description": "Represents an HL7v2 store.",
  "properties": {
    "labels": {
      "additionalProperties": {
        "type": "string"
      },
      "description": "User-supplied key-value pairs used to organize HL7v2 stores. Label keys must be between 1 and 63 characters long, have a UTF-8 encoding of maximum 128 bytes, and must conform to the following PCRE regular expression: \\p{Ll}\\p{Lo}{0,62} Label values are optional, must be between 1 and 63 characters long, have a UTF-8 encoding of maximum 128 bytes, and must conform to the following PCRE regular expression: [\\p{Ll}\\p{Lo}\\p{N}_-]{0,63} No more than 64 labels can be associated with a given store.",
      "type": "object"
    },
    "name": {
      "description": "Identifier. Resource name of the HL7v2 store, of the form `projects/{project_id}/locations/{location_id}/datasets/{dataset_id}/hl7V2Stores/{hl7v2_store_id}`.",
      "type": "string"
    },
    "notificationConfigs": {
      "description": "A list of notification configs. Each configuration uses a filter to determine whether to publish a message (both Ingest & Create) on the corresponding notification destination. Only the message name is sent as part of the notification. Supplied by the client.",
      "items": {
        "$ref": "#/components/schemas/Hl7V2NotificationConfig"
      },
      "type": "array"
    },
    "parserConfig": {
      "$ref": "#/components/schemas/ParserConfig",
      "description": "The configuration for the parser. It determines how the server parses the messages."
    },
    "rejectDuplicateMessage": {
      "description": "Determines whether to reject duplicate messages. A duplicate message is a message with the same raw bytes as a message that has already been ingested/created in this HL7v2 store. The default value is false, meaning that the store accepts the duplicate messages and it also returns the same ACK message in the IngestMessageResponse as has been returned previously. Note that only one resource is created in the store. When this field is set to true, CreateMessage/IngestMessage requests with a duplicate message will be rejected by the store, and IngestMessageErrorDetail returns a NACK message upon rejection.",
      "type": "boolean"
    }
  },
  "type": "object"
}

=== api-evangelist/google-cloud-healthcare/examples/Hl7V2Store-example.json
{
  "labels": {},
  "name": "example-string",
  "notificationConfigs": [
    {
      "filter": {},
      "pubsubTopic": {}
    }
  ],
  "parserConfig": {
    "allowNullHeader": true,
    "schema": {},
    "segmentTerminator": "example-string",
    "version": "PARSER_VERSION_UNSPECIFIED"
  },
  "rejectDuplicateMessage": true
}
